version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Verificando versión de Terraform..."
      - terraform --version

  pre_build:
    commands:
      - echo "Inicializando Terraform..."
      - cd DEPLOYMENT
      - terraform init

  build:
    commands:
      - echo "Aplicando Terraform..."
      - terraform apply -auto-approve

artifacts:
  files:
    - "**/*"
