project_name = "jcarraag-TFG"
environment  = "dev"
aws_region   = "eu-central-1"
vpc_cidr     = "10.0.0.0/16"
GitHubOwner  = "Jorgemyte"         
GitHubRepo   = "SUIT-jcarraag-tfg"  
approval_email = "jcarraag@emeal.nttdata.com"
